version: '3.8'
services:
  backend:
    container_name: api-service
    restart: always
    build: .
    ports:
      - '9000:9000'
    environment:
      - MONGO_USERNAME=hamlet
      - MONGO_PASSWORD=toor
      - NODE_ENV=production
    volumes:
      - ./logs:/service/logs
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    restart: always
    image: mongo
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=hamlet
      - MONGO_INITDB_ROOT_PASSWORD=toor
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
